# Introducción

### Vamos a analizar un conjunto de datos de canciones y sus estadísticas por semanas: listas_musica.csv
### Es un conjunto de datos que nos permite trabajar los conceptos de pandas y numpy.
### El ejercicio será guiado aunque se permite no ver las soluciones para realizar las tareas.

### Las columnas del dataset son:

### date: Tipo date - Fecha de la lista.
### rank: Tipo int - Posición del ranking de la canción en esa fecha.
### ong: Tipo str - Nombre de la canción.
### artist: Tipo str - Artista.
### last-week: Tipo int - Posición en el ranking de la semana anterior.
### peak-rank: Tipo int - La mejor posición de la canción en el ranking.
### weeks-on-board: Tipo int - Número de semanas que la canción lleva en la lista.

### Carga de librerías
### Cargue las librerías numpy, pandas y os.

In [1]:
#CARGAMOS TODAS LAS LIBRERIAS QUE NOS PIDEN 
import numpy as np
import pandas as pd
import os

### Carga del dataset
### Lea el dataset y conviértalo en un dataframe.

### Imprima el dataset una vez lo tenga.

In [2]:
# Cargar los datos desde el archivo CSV en URL_data
URL_data = r'C:\Users\34650\Desktop\BOOTCAMP\temario\PROYECTO(MODULO1)\LISTA MUSICA\listas_musica.csv'

In [3]:
#Leemos el archivo csv (URL) y creamos un DataFRame(df1)
df1 =pd.read_csv(URL_data)

In [4]:
df1

,date,rank,song,artist,last-week,peak-rank,weeks-on-board
0,2021-11-06,1,Easy On Me,Adele,1.0,1,3
1,2021-11-06,2,Stay,The Kid LAROI & Justin Bieber,2.0,1,16
2,2021-11-06,3,Industry Baby,Lil Nas X & Jack Harlow,3.0,1,14
3,2021-11-06,4,Fancy Like,Walker Hayes,4.0,3,19
4,2021-11-06,5,Bad Habits,Ed Sheeran,5.0,2,18
...,...,...,...,...,...,...,...
330082,1958-08-04,96,Over And Over,Thurston Harris,NaN,96,1
330083,1958-08-04,97,I Believe In You,Robert & Johnny,NaN,97,1
330084,1958-08-04,98,Little Serenade,The Ames Brothers,NaN,98,1
330085,1958-08-04,99,I'll Get By (As Long As I Have You),Billy Williams,NaN,99,1
330086,1958-08-04,100,Judy,Frankie Vaughan,NaN,100,1

# Limpieza de datos
Rellene con 0 usando fillna().

In [5]:
#Le damos el valor de DF modificado, con los valores nulos en 0
df1 = df1.fillna(0)

In [6]:
df1

,date,rank,song,artist,last-week,peak-rank,weeks-on-board
0,2021-11-06,1,Easy On Me,Adele,1.0,1,3
1,2021-11-06,2,Stay,The Kid LAROI & Justin Bieber,2.0,1,16
2,2021-11-06,3,Industry Baby,Lil Nas X & Jack Harlow,3.0,1,14
3,2021-11-06,4,Fancy Like,Walker Hayes,4.0,3,19
4,2021-11-06,5,Bad Habits,Ed Sheeran,5.0,2,18
...,...,...,...,...,...,...,...
330082,1958-08-04,96,Over And Over,Thurston Harris,0.0,96,1
330083,1958-08-04,97,I Believe In You,Robert & Johnny,0.0,97,1
330084,1958-08-04,98,Little Serenade,The Ames Brothers,0.0,98,1
330085,1958-08-04,99,I'll Get By (As Long As I Have You),Billy Williams,0.0,99,1
330086,1958-08-04,100,Judy,Frankie Vaughan,0.0,100,1

# Imprima algunos valores de ejemplos
Use tail() para imprimir algunos valores.

In [7]:
#Para ver los ultimos 5 filas de la cola
df1.tail(10)

,date,rank,song,artist,last-week,peak-rank,weeks-on-board
330077,1958-08-04,91,The Purple People Eater Meets The Witch Doctor,Joe South,0.0,91,1
330078,1958-08-04,92,Bird Dog,The Everly Brothers,0.0,92,1
330079,1958-08-04,93,Are You Really Mine,Jimmie Rodgers,0.0,93,1
330080,1958-08-04,94,She Was Only Seventeen (He Was One Year More),Marty Robbins,0.0,94,1
330081,1958-08-04,95,Little Mary,Fats Domino,0.0,95,1
330082,1958-08-04,96,Over And Over,Thurston Harris,0.0,96,1
330083,1958-08-04,97,I Believe In You,Robert & Johnny,0.0,97,1
330084,1958-08-04,98,Little Serenade,The Ames Brothers,0.0,98,1
330085,1958-08-04,99,I'll Get By (As Long As I Have You),Billy Williams,0.0,99,1
330086,1958-08-04,100,Judy,Frankie Vaughan,0.0,100,1

# Calcule los top 30 artistas
Puede usar la función value_counts() y head(...).

Fíjese en usar la columna correspondiente.

In [8]:
top_30_artistas = df1['artist'].value_counts().head(30)

In [9]:
top_30_artistas

artist
Taylor Swift             1023
Elton John                889
Madonna                   857
Drake                     787
Kenny Chesney             769
Tim McGraw                731
Keith Urban               673
Stevie Wonder             659
Rod Stewart               657
Mariah Carey              621
Michael Jackson           611
Chicago                   607
Rascal Flatts             604
Billy Joel                588
The Rolling Stones        585
The Beatles               585
Jason Aldean              572
Aretha Franklin           569
Rihanna                   566
P!nk                      564
Whitney Houston           561
Brad Paisley              559
Neil Diamond              553
George Strait             553
Luke Bryan                543
Carrie Underwood          541
Daryl Hall John Oates     540
The Beach Boys            531
Toby Keith                526
Bee Gees                  516
Name: count, dtype: int64

 Muestre el top 15 de canciones junto con su cantante

In [10]:
top_15 = df1[['artist','song']].value_counts().head(15)

print(top_15)

artist                                     song
The Weeknd                                 Blinding Lights                        90
Imagine Dragons                            Radioactive                            87
AWOLNATION                                 Sail                                   79
Jason Mraz                                 I'm Yours                              76
LeAnn Rimes                                How Do I Live                          69
LMFAO Featuring Lauren Bennett & GoonRock  Party Rock Anthem                      68
OneRepublic                                Counting Stars                         68
Jewel                                      Foolish Games/You Were Meant For Me    65
Adele                                      Rolling In The Deep                    65
Carrie Underwood                           Before He Cheats                       64
The Lumineers                              Ho Hey                                 62
Lifehouse                                  You And Me                             62
Gabby Barrett Featuring Charlie Puth       I Hope                                 62
Post Malone                                Circles                                61
Imagine Dragons                            Demons                                 61
Name: count, dtype: int64

Muestre el top 10 de los artistas, canciones y su mejor posición

In [11]:
top_10 = df1[['artist','song','peak-rank']].value_counts().head(10)

In [12]:
top_10

artist                                     song                     peak-rank
The Weeknd                                 Blinding Lights          1            74
Ed Sheeran                                 Shape Of You             1            58
Jason Mraz                                 I'm Yours                6            56
LMFAO Featuring Lauren Bennett & GoonRock  Party Rock Anthem        1            54
The Black Eyed Peas                        I Gotta Feeling          1            54
Justin Timberlake                          Can't Stop The Feeling!  1            52
Taylor Swift                               Shake It Off             1            50
The Chainsmokers Featuring Halsey          Closer                   1            50
Post Malone                                Circles                  1            50
Mark Ronson Featuring Bruno Mars           Uptown Funk!             1            49
Name: count, dtype: int64

Artistas más reproducidos por semanas¶
Transforme la columna date en datetime.

Use set_index para crear un índice en la columna date.

Imprima el dataframe con el nuevo índice.

In [ ]:

# Transformamos la columna 'date' en datetime
df1['date'] = df1['date'].apply(pd.to_datetime)

# Usamos .set_index para remplazar como indice
df1.set_index('date', inplace=True)

In [28]:
df1

,rank,song,artist,last-week,peak-rank,weeks-on-board
date,,,,,,
2021-11-06,1,Easy On Me,Adele,1.0,1,3
2021-11-06,2,Stay,The Kid LAROI & Justin Bieber,2.0,1,16
2021-11-06,3,Industry Baby,Lil Nas X & Jack Harlow,3.0,1,14
2021-11-06,4,Fancy Like,Walker Hayes,4.0,3,19
2021-11-06,5,Bad Habits,Ed Sheeran,5.0,2,18
...,...,...,...,...,...,...
1958-08-04,96,Over And Over,Thurston Harris,0.0,96,1
1958-08-04,97,I Believe In You,Robert & Johnny,0.0,97,1
1958-08-04,98,Little Serenade,The Ames Brothers,0.0,98,1
1958-08-04,99,I'll Get By (As Long As I Have You),Billy Williams,0.0,99,1
1958-08-04,100,Judy,Frankie Vaughan,0.0,100,1

Encuentre los más y menos escuchados según un intervalo de tiempo
Puede usar resample(frecuencia)[columna].

Las frecuencias que puede usar son:

H - Horaria
D - Diaria
W - Semanal
M - Mensual
A - Anual
Puede usar .agg([columnas]) para agregar los datos

In [36]:

# Definimos la frecuencia de resampling, por ejemplo, 'D' para días
frecuencia = 'D'

# Resample los datos para sumar las veces que se ha escuchado cada canción en cada intervalo
df_resampled = df1.resample(frecuencia)['weeks-on-board'].sum()

# Ordenar las canciones más y menos escuchadas
canciones_mas_escuchadas = df_resampled.sort_values(ascending=False)
canciones_menos_escuchadas = df_resampled.sort_values()

# Mostrar las canciones más escuchadas
print("Las canciones más escuchadas son:")
print(canciones_mas_escuchadas)

# Mostrar las canciones menos escuchadas
print("\nLas canciones menos escuchadas son:")
print(canciones_menos_escuchadas)

Las canciones más escuchadas son:
date
2013-01-19    1510
2013-02-02    1503
2014-03-08    1497
2013-02-09    1479
2014-03-01    1461
              ...
1985-09-12       0
1985-09-11       0
1985-09-10       0
1985-09-09       0
1990-03-22       0
Name: weeks-on-board, Length: 23106, dtype: int64

Las canciones menos escuchadas son:
date
1990-03-21       0
2015-10-28       0
1994-09-30       0
1994-09-29       0
1994-09-28       0
              ...
2014-03-01    1461
2013-02-09    1479
2014-03-08    1497
2013-02-02    1503
2013-01-19    1510
Name: weeks-on-board, Length: 23106, dtype: int64